# Generated by Django 6.0.5 on 2026-09-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
